### PR TITLE
show trusted status for images

### PR DESCRIPTION
**Pull request by juhmelo**
pierone now returns `trusted` status for images.
Adding trusted column to `pierone tags` to expose this information.

### CODE REVIEW

**Comment by lotharschulz** [comment]
What about a test e.g. `test_trusted` similar to [test_tags](https://github.com/zalando-stups/pierone-cli/blob/master/tests/test_cli.py#L219) and others?

**Comment by juhmelo** [comment]
:+1:

**Comment by ethercrow** [comment]
:+1:

**Comment by lotharschulz** [comment]
👍

**Pull request merged**
