### PR TITLE
#58 delete credsStore property in the config object loaded from config.json

### LINKED ISSUE #58: no basic auth credentials
Today I had an auth issue. While trying to do `docker push` I was getting the following log:

    ➜ pierone login             
    Getting OAuth2 token "pierone".. OK
    Storing Docker client configuration in /Users/whoever/.docker/config.json.. OK
    ➜ docker push myrepo/...
    The push refers to a repository [myrepo/...]
    a5f591aacc10: Preparing 
    ...
    cb11ba605400: Waiting 
    no basic auth credentials

Recreating `~/config.json` saved me.  
There was `"credsStore": "osxkeychain"` setting In the previous version of the `~/config.json` which was causing me troubles.

BTW 
mac os 10.12.3
pierone cli 1.1.27
docker 17.06.0-ce, build 02c1d87

### PR DESCRIPTION
**Pull request by luisfarzati**
Fixes #58 -- still some work needed in order to properly test.

### CODE REVIEW

**Comment by Raffo** [comment]
@hjacobs The problem looks like it is coming from pierone/api.py line 65 where we read from the local config instead of the temp file.

**Comment by Raffo** [comment]
Ok I figured out the problem, pushed a commit with @luisfarzati , should work now!

**Comment by Raffo** [comment]
@hjacobs please review.

**Comment by luisfarzati** [comment]
ty @Raffo :)

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
